apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-db-deployment
  labels:
    app: review-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-db
  template:
    metadata:
      labels:
        app: review-db
    spec:
      containers:
        - name: review-db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: reviewDB
            - name: MYSQL_ROOT_PASSWORD
              value: root
